[package]
name = "dagger-lsp-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dagger-core = { path = "../../crates/core" }
dagger-lsp-client = { path = "../../crates/lsp-client" }
dagger-protocol = { path = "../../crates/protocol" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
