[snapshots]
adapter = "target/debug/dagger-git"

[[extractors]]
adapter = "target/debug/dagger-rust"

[review]
ignore = ["Cargo.lock", "flake.lock", "dagger-demo.html"]

[[groupings]]
name = "crate"
marker = "Cargo.toml"
