[package]
name = "dagger-ui"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "Reads a dagger review"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
