/* What dagger says, written from the types that say it.
 *
 * Generated by crates/typescript — don't edit, run ./check. The shapes the page
 * makes for itself live in dagger.ts, which is written by hand because nothing in
 * Rust knows about them.
 */

export type Identity = number;

export type Part = "type" | "body" | "docs";

export type Span = { start: number, end: number, };

export type Piece = { text: string, span: Span, 
/**
 * Set when this piece lives somewhere other than the definition's own file, the
 * way a C declaration sits in a header away from its body.
 */
file: string | null, };

export type Locator = { scope: Array<string>, name: string, };

export type Occurrence = { locator: Locator, 
/**
 * What the extractor calls this, like "function" or "test". We never read it.
 */
kind: string, 
/**
 * Where the definition lives, and where its parts live unless they say otherwise.
 */
file: string, 
/**
 * The source, split up for the reader. Only used for display and for checking that
 * every changed byte belongs somewhere. Each part's pieces are in the order they
 * appear, which is the order a reader would meet them.
 */
parts: { [key in Part]?: Array<Piece> }, 
/**
 * How the definition looks from outside, according to the compiler. Not found
 * anywhere in the source, which is why it sits apart from the parts.
 *
 * This decides whether callers broke, so when it's here it beats the type part,
 * and a change to an inferred return type can't pass as a body change. An
 * extractor that supplies it can dump the whole definition into one part and
 * still get every downstream answer right. It just won't read as nicely.
 */
contract: string | null, };

export type Sides = { "added": Occurrence } | { "removed": Occurrence } | { "kept": { before: Occurrence, after: Occurrence, } };

export type Definition = { identity: Identity, sides: Sides, };

export type Edits = { 
/**
 * How it looks to callers, including its name.
 */
contract: boolean, 
/**
 * Landed in a different file or scope. Nobody breaks over this, so on its own
 * it isn't worth reviewing.
 */
moved: boolean, 
/**
 * The parts whose text differs.
 */
parts: Array<Part>, };

export type Change = "added" | "removed" | { "kept": Edits };

export type Edge = { from: Identity, to: Identity, 
/**
 * Definitions the chain passed through on the way, in order. Empty when the two
 * mention each other directly.
 */
via: Array<Identity>, };

export type Diagnostic = { "lopsided_contract": { definition: Identity, } } | { "unbound_in_contract": { definition: Identity, symbol: string, } } | { "mention_from_nowhere": { from: Locator, } } | { "two_of_one_name": { locator: Locator, times: number, } } | { "unattributed": { file: string, lines: number, 
/**
 * The first few, so this can be looked into rather than just counted.
 */
at: Array<number>, } };

export type Review = { changes: { [key in Identity]: Change }, 
/**
 * Didn't change, but sits downstream of something that did.
 */
affected: Array<Identity>, 
/**
 * Worth reading: what changed, and what a change reached.
 */
members: Array<Identity>, 
/**
 * Not worth reading, but the reading doesn't make sense without it on the page.
 *
 * A module is where its definitions live, and a page draws it as the box around them.
 * Left out when nothing about the module itself changed, that box stands for nothing —
 * it can't be pointed at, and an edge that ends at it has nowhere to land. Putting it
 * among the members instead would mean asking somebody to read a file's imports
 * because something else in the file changed, which is a waste of the one thing this
 * tool is trying to save.
 */
context: Array<Identity>, edges: Array<Edge>, diagnostics: Array<Diagnostic>, };

export type Cost = { 
/**
 * The most that was in the reader's head at once.
 */
peak_open: number, 
/**
 * Added up over every step, so a long shallow reading can be told apart from a
 * short deep one.
 */
total_open: number, taken_on_faith: number, 
/**
 * Steps that landed somewhere other than the one before: another package, or failing
 * a grouping, another file.
 */
jumps: number, };

export type Step = { definition: Identity, 
/**
 * What this leans on that hasn't been read yet. Only ever non-empty inside a
 * circle, and kept as short as we can manage.
 */
on_faith: Array<Identity>, };

export type Ordering = { steps: Array<Step>, 
/**
 * How this reading went, so one rule can be argued against another with numbers
 * from real changes rather than taste.
 */
cost: Cost, };

export type Grouping = { 
/**
 * What a reader would call this way of grouping: "package", "owner", "layer".
 */
name: string, of: { [key in Identity]: Array<string> }, };

export type Note = { message: string, 
/**
 * The file it's about, when it's about one.
 */
file: string | null, };

