/* What dagger says, written from the types that say it.
 *
 * Generated by crates/typescript — don't edit, run ./check. The shapes the page
 * makes for itself live in dagger.ts, which is written by hand because nothing in
 * Rust knows about them.
 */

export type Identity = string;

export type Part = "type" | "body" | "docs";

export type Span = { start: number, end: number, };

export type Piece = { text: string, span: Span, 
/**
 * Which line of the file this starts on, counting from one.
 *
 * A span is where the bytes are, which is what the machinery needs and nothing a
 * person can use. A reader points at a line — "the check on line 31" — and only
 * whoever read the file can say which line that is, so it's said here rather than
 * worked out later from text nobody kept.
 */
line: number, 
/**
 * Which file this stretch is in.
 *
 * Always said, even when it's the definition's own. It used to be set only when it
 * differed, which made one place spell itself two ways — and everything comparing two
 * pieces had to know that, or quietly decide that a piece saying nothing and a piece
 * naming its own file were in different files. Two bugs came of it: an overlap that
 * went unreported, and a part that read as having moved when it hadn't.
 */
file: string, };

export type Locator = { scope: Array<string>, name: string, };

export type Role = "item" | "container";

export type Occurrence = { locator: Locator, 
/**
 * Whether this holds other definitions.
 */
role: Role, 
/**
 * What it's written inside, in the language's own structure: a method's impl, an
 * impl's module, a module's module. `None` at the root.
 *
 * Said by whoever parsed the file, because only they know. Worked out afterwards from
 * the scope and the kind, it comes out wrong in the ordinary cases — a method's scope
 * names its type, not the impl block it sits in — and it costs fifty lines to be wrong
 * in.
 */
parent: Locator | null, 
/**
 * What the extractor calls this, like "function" or "test". Display only.
 */
kind: string, 
/**
 * Where the definition lives, and where its parts live unless they say otherwise.
 */
file: string, 
/**
 * The source, split up for the reader. Only used for display and for checking that
 * every changed byte belongs somewhere. Each part's pieces are in the order they
 * appear, which is the order a reader would meet them.
 */
parts: { [key in Part]?: Array<Piece> }, 
/**
 * How the definition looks from outside, according to the compiler. Not found
 * anywhere in the source, which is why it sits apart from the parts.
 *
 * This decides whether callers broke, so when it's here it beats the type part,
 * and a change to an inferred return type can't pass as a body change. An
 * extractor that supplies it can dump the whole definition into one part and
 * still get every downstream answer right. It just won't read as nicely.
 */
contract: string | null, };

export type Sides = { "added": Occurrence } | { "removed": Occurrence } | { "kept": { before: Occurrence, after: Occurrence, } };

export type Definition = { 
/**
 * Whether it holds others. Said by whoever read the file.
 */
role: Role, 
/**
 * What it was on each side.
 */
sides: Sides, 
/**
 * What happened to it.
 */
change: Change, 
/**
 * How many hops away the nearest change that reached it is. Never nought: whether it
 * changed on its own account is what `change` is for, and a definition can be both.
 */
reached: number | null, 
/**
 * What it's written inside. Always present in this review when it isn't `None`.
 */
parent: Identity | null, 
/**
 * The group its file belongs to, matching one of the paths in `groups`.
 */
group: Array<string> | null, };

export type Group = { 
/**
 * Outermost first. Written as it is rather than joined, so nothing has to agree on a
 * separator that a path component might contain.
 */
path: Array<string>, 
/**
 * Nought for a group that leans on no other. The page draws its rows by this and the
 * reading order follows it, which is what keeps a reading running down the page.
 */
band: number, };

export type Impact = "incomplete" | "degraded";

export type Warning = { impact: Impact, 
/**
 * Worded here rather than on the page, so there's one wording rather than one per
 * reader, and so the names in it can be looked up while they're still to hand.
 */
message: string, 
/**
 * What it's about, when it's about one definition. For pointing somebody at it.
 */
about: Identity | null, };

export type Edits = { 
/**
 * How it looks to callers, including its name.
 */
contract: boolean, 
/**
 * Landed in a different file or scope. Nobody breaks over this, so on its own
 * it isn't worth reviewing.
 */
moved: boolean, 
/**
 * The parts whose text differs.
 */
parts: Array<Part>, };

export type Change = "added" | "removed" | { "kept": Edits };

export type Edge = { from: Identity, to: Identity, };

export type Diagnostic = { "lopsided_contract": { definition: Identity, } } | { "unbound_in_contract": { definition: Identity, symbol: string, } } | { "mention_from_nowhere": { from: Locator, } } | { "tangled": { definition: Locator, 
/**
 * Where the trouble starts, in bytes.
 */
at: number, } } | { "two_of_one_name": { locator: Locator, times: number, } } | { "unattributed": { file: string, lines: number, 
/**
 * The first few, so this can be looked into rather than just counted.
 */
at: Array<number>, } };

export type Review = { definitions: { [key in Identity]: Definition }, 
/**
 * What to read, in order. Whatever a step names is worth reading; everything else in
 * `definitions` is here to be drawn around it.
 */
reading: Array<Step>, edges: Array<Edge>, groups: Array<Group>, 
/**
 * What a reader calls the grouping: "package", "crate".
 */
grouping: string | null, 
/**
 * How far this reading was told to follow a change outward.
 */
ripples: number, cost: Cost, warnings: Array<Warning>, };

export type Cost = { 
/**
 * The most that was in the reader's head at once.
 */
peak_open: number, 
/**
 * Added up over every step, so a long shallow reading can be told apart from a
 * short deep one.
 */
total_open: number, taken_on_faith: number, 
/**
 * Steps that landed somewhere other than the one before: another package, or failing
 * a grouping, another file.
 */
jumps: number, };

export type Step = { definition: Identity, 
/**
 * What this leans on that hasn't been read yet. Only ever non-empty inside a
 * circle, and kept as short as we can manage.
 */
on_faith: Array<Identity>, };

export type Ordering = { steps: Array<Step>, 
/**
 * How this reading went, so one rule can be argued against another with numbers
 * from real changes rather than taste.
 */
cost: Cost, };

export type Note = { message: string, 
/**
 * The file it's about, when it's about one.
 */
file: string | null, };

