/* What dagger says, written from the types that say it.
 *
 * Generated by crates/typescript — don't edit, run ./check. The shapes the page
 * makes for itself live in dagger.ts, which is written by hand because nothing in
 * Rust knows about them.
 */

export type Identity = string;

export type Part = "type" | "body" | "docs";

export type Span = { start: number, end: number, };

export type Piece = { text: string, span: Span, 
/**
 * Line this starts on, from one. Spans are byte offsets, which readers can't use, and
 * only the extractor that read the file knows the line.
 */
line: number, 
/**
 * Always set, even when it's the definition's own file, so two pieces can be compared
 * without knowing about a default.
 */
file: string, };

export type Locator = { scope: Array<string>, name: string, };

export type Role = "item" | "container";

export type Occurrence = { locator: Locator, 
/**
 * Whether this holds other definitions.
 */
role: Role, 
/**
 * What it's written inside: a method's impl, an impl's module. `None` at the root.
 * Set by the extractor, because deriving it from scope and kind gets ordinary cases
 * wrong (a method's scope names its type, not its impl block).
 */
parent: Locator | null, 
/**
 * What the extractor calls this, like "function" or "test". Display only.
 */
kind: string, 
/**
 * Where the definition lives, and where its parts live unless they say otherwise.
 */
file: string, 
/**
 * The source, split up for display and for checking that every changed byte belongs
 * somewhere. Each part's pieces are in source order.
 */
parts: { [key in Part]?: Array<Piece> }, 
/**
 * The compiler's view of the definition from outside; not in the source, so kept
 * apart from the parts. When present it overrides the type part for deciding whether
 * callers broke, so an inferred return type change can't pass as a body change.
 */
type_from_compiler: string | null, };

export type Sides = { "added": Occurrence } | { "removed": Occurrence } | { "kept": { before: Occurrence, after: Occurrence, } };

export type Definition = { 
/**
 * Whether it holds others. Said by whoever read the file.
 */
role: Role, 
/**
 * What it was on each side.
 */
sides: Sides, 
/**
 * What happened to it.
 */
change: Change, 
/**
 * Hops from the nearest change that reached it. Never zero: its own change is `change`.
 */
reached: number | null, 
/**
 * The one word for what happened to it, as every rendering shows it.
 */
mark: Mark, 
/**
 * What it's written inside. Always present in this review when it isn't `None`.
 */
parent: Identity | null, };

export type Group = { "type": "group", name: string, 
/**
 * Zero if it depends on nothing else in its holder, else one more than its deepest dependency.
 */
tier: number, 
/**
 * Tiers ascending, and along a tier in reading order.
 */
children: Array<Group>, } | { "type": "node", id: Identity, tier: number, };

export type Impact = "incomplete" | "degraded";

export type Warning = { impact: Impact, 
/**
 * Worded here rather than on the page, so there's one wording and names can be
 * looked up while they're still to hand.
 */
message: string, 
/**
 * What it's about, when it's about one definition. For pointing somebody at it.
 */
about: Identity | null, };

export type Edits = { 
/**
 * How it looks to callers, including its name.
 */
type_changed: boolean, 
/**
 * Landed in a different file or scope. Nobody breaks over this, so on its own
 * it isn't worth reviewing.
 */
moved: boolean, 
/**
 * The parts whose text differs.
 */
parts: Array<Part>, };

export type Change = "added" | "removed" | { "kept": Edits };

export type Mark = "added" | "removed" | "type" | "body" | "docs" | "reached" | "untouched";

export type Edge = { from: Identity, to: Identity, };

export type Diagnostic = { "lopsided_type": { definition: Identity, } } | { "unbound_in_type": { definition: Identity, symbol: string, } } | { "mention_from_nowhere": { from: Locator, } } | { "tangled": { definition: Locator, 
/**
 * Where the trouble starts, in bytes.
 */
at: number, } } | { "two_of_one_name": { locator: Locator, times: number, } } | { "unattributed": { file: string, lines: number, 
/**
 * The first few, so this can be looked into rather than just counted.
 */
at: Array<number>, } };

export type Review = { 
/**
 * The commit's title, when the adapter knows one. A directory has no commit message.
 */
title: string | null, definitions: { [key in Identity]: Definition }, 
/**
 * What to read, in order. Whatever a step names is worth reading; everything else in
 * `definitions` is here to be drawn around it.
 */
reading: Array<Step>, edges: Array<Edge>, 
/**
 * Everything drawn, as it nests and stacks, so the reading and the page can't disagree.
 */
groups: Array<Group>, 
/**
 * What a reader calls the grouping: "package", "crate".
 */
grouping: string | null, 
/**
 * How far this review was told to follow a change outward.
 */
ripples: number, cost: Cost, warnings: Array<Warning>, };

export type Cost = { 
/**
 * The most open at once.
 */
peak_open: number, 
/**
 * Summed over every step, to tell a long shallow reading from a short deep one.
 */
total_open: number, taken_on_faith: number, 
/**
 * Steps that moved to another package, or without a grouping, another file.
 */
jumps: number, };

export type Step = { definition: Identity, 
/**
 * Dependencies not yet read. Only non-empty inside a cycle.
 */
on_faith: Array<Identity>, };

export type Ordering = { steps: Array<Step>, 
/**
 * Numbers for comparing one ordering rule against another on real changes.
 */
cost: Cost, };

export type Note = { message: string, 
/**
 * The file it's about, when it's about one.
 */
file: string | null, };

/** Each mark's glyph and wording, in the order a legend lists them. */
export const LEGEND = [
  ["added", "+", "added"],
  ["removed", "-", "removed"],
  ["type", "!", "type changed"],
  ["body", "~", "body changed"],
  ["docs", "\"", "docs changed"],
  ["reached", "=", "reached, unchanged"],
  ["untouched", ".", "untouched"],
] as const;

