[package]
name = "dagger-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dagger-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
ts-rs = { version = "12", optional = true }

[features]
typescript = ["dep:ts-rs", "dagger-core/typescript"]
