//! Writes the TypeScript types for everything dagger emits, generated from the Rust types
//! so the page and the JSON can't drift apart. `./check` fails when the output is stale.
//!
//! Only what dagger emits: the shapes the page makes for itself live in dagger.ts.

use anyhow::{Context, Result};
use dagger_core::change::{Change, Edits, Mark};
use dagger_core::diagnostic::Diagnostic;
use dagger_core::model::{Identity, Locator, Occurrence, Part, Piece, Role, Sides, Span};
use dagger_core::order::{Cost, Ordering, Step};
use dagger_core::review::{Definition, Edge, Impact, Review, Warning};
use dagger_core::shape::Group;
use dagger_protocol::Note;
use std::io::Write;
use ts_rs::{Config, TS};

fn main() -> Result<()> {
    let mut out = String::from(
        "/* What dagger says, written from the types that say it.\n\
         \x20*\n\
         \x20* Generated by crates/typescript — don't edit, run ./check. The shapes the page\n\
         \x20* makes for itself live in dagger.ts, which is written by hand because nothing in\n\
         \x20* Rust knows about them.\n\
         \x20*/\n\n",
    );

    let how = Config::default();
    for declaration in [
        Identity::decl(&how),
        Part::decl(&how),
        Span::decl(&how),
        Piece::decl(&how),
        Locator::decl(&how),
        Role::decl(&how),
        Occurrence::decl(&how),
        Sides::decl(&how),
        Definition::decl(&how),
        Group::decl(&how),
        Impact::decl(&how),
        Warning::decl(&how),
        Edits::decl(&how),
        Change::decl(&how),
        Mark::decl(&how),
        Edge::decl(&how),
        Diagnostic::decl(&how),
        Review::decl(&how),
        Cost::decl(&how),
        Step::decl(&how),
        Ordering::decl(&how),
        Note::decl(&how),
    ] {
        out.push_str("export ");
        out.push_str(declaration.trim_end_matches(';'));
        out.push_str(";\n\n");
    }

    // The legend is values, not a type, so it's written out by hand from the same table
    // the terminal prints.
    out.push_str("/** Each mark's glyph and wording, in the order a legend lists them. */\n");
    out.push_str("export const LEGEND = [\n");
    for mark in Mark::ALL {
        let name = serde_json::to_string(&mark)?;
        out.push_str(&format!(
            "  [{name}, {}, {}],\n",
            serde_json::to_string(&mark.glyph().to_string())?,
            serde_json::to_string(mark.label())?
        ));
    }
    out.push_str("] as const;\n\n");

    let to = std::env::args().nth(1).context("say where to write it")?;
    let mut file = std::fs::File::create(&to).with_context(|| format!("couldn't write {to}"))?;
    file.write_all(out.as_bytes())?;
    Ok(())
}
