//! Writes the TypeScript for everything dagger says, so the page doesn't have to guess.
//!
//! The page used to describe these shapes itself, and nothing checked the two agreed. A
//! renamed field doesn't fail there: TypeScript is satisfied by the declaration it was
//! given, and the value simply arrives undefined at the one moment nobody is watching. So
//! the declarations come from the types that produce the JSON, and `./check` fails when
//! what's written down stops matching them.
//!
//! Only what dagger emits, all the way out: `Said` is the whole document, so nothing is
//! left for the page to describe by hand. The shapes the page makes for itself — a laid-out
//! box, a node's place on screen — are its own business, and describing those in Rust would
//! mean inventing types to describe a drawing.

use anyhow::{Context, Result};
use dagger_core::change::{Change, Edits};
use dagger_core::diagnostic::Diagnostic;
use dagger_core::model::{Identity, Locator, Occurrence, Part, Piece, Role, Sides, Span};
use dagger_core::order::{Cost, Ordering, Step};
use dagger_core::review::{Definition, Edge, Impact, Review, Warning};
use dagger_core::shape::Group;
use dagger_protocol::Note;
use std::io::Write;
use ts_rs::{Config, TS};

fn main() -> Result<()> {
    let mut out = String::from(
        "/* What dagger says, written from the types that say it.\n\
         \x20*\n\
         \x20* Generated by crates/typescript — don't edit, run ./check. The shapes the page\n\
         \x20* makes for itself live in dagger.ts, which is written by hand because nothing in\n\
         \x20* Rust knows about them.\n\
         \x20*/\n\n",
    );

    let how = Config::default();
    for declaration in [
        Identity::decl(&how),
        Part::decl(&how),
        Span::decl(&how),
        Piece::decl(&how),
        Locator::decl(&how),
        Role::decl(&how),
        Occurrence::decl(&how),
        Sides::decl(&how),
        Definition::decl(&how),
        Group::decl(&how),
        Impact::decl(&how),
        Warning::decl(&how),
        Edits::decl(&how),
        Change::decl(&how),
        Edge::decl(&how),
        Diagnostic::decl(&how),
        Review::decl(&how),
        Cost::decl(&how),
        Step::decl(&how),
        Ordering::decl(&how),
        Note::decl(&how),
    ] {
        out.push_str("export ");
        out.push_str(declaration.trim_end_matches(';'));
        out.push_str(";\n\n");
    }

    let to = std::env::args().nth(1).context("say where to write it")?;
    let mut file = std::fs::File::create(&to).with_context(|| format!("couldn't write {to}"))?;
    file.write_all(out.as_bytes())?;
    Ok(())
}
